---
- name: Install docker
  hosts: localhost
  become: yes
  vars:
        packages:
                - docker-ce
                - docker-ce-cli
                - containerd.io
                - docker-buildx-plugin
                - docker-compose-plugin
        
  tasks:
        - name: update
          yum:
                  update_cache: yes

        - name: install yum utils
          yum:
                  name: yum-utils
                  state: present

        - name: docker repo
          get_url:
                  url: https://download.docker.com/linux/rhel/docker-ce.repo
                  dest: /etc/yum.repos.d/
                  mode: '0644'

        - name: install docker
          yum:
                  name: "{{ packages }}"
                  state: present

        - name: start and enable docker
          systemd:
                  name: docker
                  enabled: yes
                  state: started


