---
- name: Install OWASP
  hosts: localhost
  become: yes
  vars:
          project_dir: "/path/to/project"  # Replace with your actual project directory
          report_dir: "/opt/dependency-check/reports"
          dependency_check_version: "8.3.1"
          dependency_check_url:  "https://github.com/jeremylong/DependencyCheck/releases/download/v{{ dependency_check_version }}/dependency-check-{{ dependency_check_version }}-release.zip"

  tasks:
          - name: Create directory for OWASP Dependency-Check
            file:
                    path: /opt/dependency-check
                    state: directory
                    mode: '0755'

          - name: Install unzip to handle .zip files
            yum:
                    name: unzip
                    state: present

          - name: Download OWASP dependency-check
            get_url:
                    url: "{{ dependency_check_url }}"
                    dest: /opt/dependency-check/dependency-check.zip

          - name: Extract OWASP dependency-check
            unarchive:
                    src: /opt/dependency-check/dependency-check.zip
                    dest: /opt/dependency-check
                    remote_src: yes


          - name: Create directory for reports
            file:
                    path: "{{ report_dir }}"
                    state: directory
                    mode: '0755'
      
          - name: Run OWASP Dependency-Check scan
            command: "/opt/dependency-check/dependency-check/bin/dependency-check.sh --project MyProject --scan {{ project_dir }} --out {{ report_dir }} --format HTML"
            args:
                    chdir: /opt/dependency-check
            register: dependency_check_result
      
          - name: Display OWASP Dependency-Check scan result
            debug:
                    msg: "{{ dependency_check_result.stdout }}"                    
